# Define the build version
version: 1.1.0-dev-{build}

image: Visual Studio 2022


init:
  - ps: Write-Host "SIGNPATH_SIGNING_REQUEST_ID= $Env:SIGNPATH_SIGNING_REQUEST_ID"
  
  
#install:
#  - ps: Install-Module -Name SignPath
#  - ps: Install-Module -Name PowerShellForGitHub 
#  - cmd: choco install gh
  
#test: off

build_script: 
  - ps: |
      if ($env:SIGNPATH_SIGNING_REQUESt_ID -eq $null)
      {
        Write-Host "SIGNPATH_SIGNING_REQUESt_ID is not set"
        exit 1
      }
      if ($env:ARTIFACTS_PATH -eq $null)
      {
        Write-Host "ARTIFACTS_PATH is not set"
        exit 1
      }

      if (-not (Test-Path .\artifacts)) {
      New-Item -ItemType Directory -Path .\artifacts
      }
  - ps: echo "Loading signed artifacts for SIGNPATH_SIGNING_REQUEST_ID=$SIGNPATH_SIGNING_REQUEST_ID"
  - ps: . .\scripts\run.ps1
  # - ps: |
  #     Get-SignedArtifact `
  #      -OrganizationId $env:SIGNPATH_ORGANIZATION_ID `
  #      -ApiToken $env:SIGNPATH_CI_USER_TOKEN `
  #      -SigningRequestId $env:SIGNPATH_SIGNING_REQUESt_ID `
  #      -OutputArtifactPath ./artifacts/Appvey.1.1.0-dev.nupkg
  - ps: Write-Host "Downloaded artifact to $ARTIFACTS_PATH"     

