name: Update Release with Signed Artifacts
on:
  push:
    branches:
      - master

jobs:
  update_release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install PowerShell Module
        shell: pwsh
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
          Install-Module -Name SignPath -Force
          
      - name: Run PowerShell script
        shell: pwsh
        env:
          ORGANIZATIONID: ${{ secrets.ORGANIZATIONID }}
          SIGNPATH_CI_USER_TOKEN: ${{ secrets.SIGNPATH_CI_USER_TOKEN }}
          SIGNING_REQUEST_ID: ${{ secrets.SIGNING_REQUEST_ID }}
        run: |
           Import-Module -Name SignPath
           ./.github/workflows/script.ps1          
      - name: Print build folder contents
        run: Get-ChildItem -Path $env:GITHUB_WORKSPACE\artifacts -Recurse
        shell: pwsh
        
        
  

        